sandbox_mode = "workspace-write"

[marketplaces.openai-bundled]
last_updated = "2026-05-07T04:13:50Z"
source_type = "local"
source = "/Users/kugeke/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-02T06:18:18Z"
source = "/Users/kugeke/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"
source_type = "local"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[projects."/Users/kugeke/Development/CloudPratica/cloud-pratica-terraform"]
trust_level = "trusted"
